modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="better_bronze"
version="1.20-1.0.4"
displayName="Better Bronze"
logoFile="better_bronze.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Makes bronze much easier to attain for any tech mods.
'''

[[dependencies.better_bronze]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_bronze]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_bronze]]
    modId="lemon_core"
    mandatory=true
    versionRange="[1.20-1.0.7,)"
    ordering="NONE"
    side="BOTH"